### ISSUE TITLE
Can we fork this repo to techbureau acount

### ISSUE THREAD

**Issue by RossyWhite** [tk1024/Zaif4PHP#4]
お世話になります。

先日先物取引のAPIをリリースしまして、これを機に、[techbureau](https://github.com/techbureau)のアカウントに
各言語のAPIラッパーを集めようとしているのですが、差支えなければ
このリポジトリを使わせてもらってもよろしいでしょうか？

**Comment by tk1024** [comment]
全然問題ないです。
自由に使ってください！

**Comment by RossyWhite** [comment]
ありがとうございます！
では、お言葉に甘えて使用させていただきます。

チケットはcloseさせていただきますね。
