### ISSUE TITLE
Market Order 成行

### ISSUE THREAD

**Issue by tz2wang** [tk1024/Zaif4PHP#5]
こんにちは、

あなたのAPIはマーケットオーダーをサポートしていますか？ 以下の書類は、市場指図ではなく、指値注文のみを記載しています。

http://techbureau-api-document.readthedocs.io/ja/latest/trade/2_individual/7_trade.html

どうか教えてください。 ありがとうございました。

**Comment by tk1024** [comment]
Not support market order.
I have not checked whether there is a market order API and This library has not been maintained for a while.

So, If you can write code, please fork this repo.
thank you.
